<a href="https://colab.research.google.com/github/Nihalht/ML_LAB-PR-s/blob/main/ML_EXP_4a.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Nihal H T lab - 4a **

Data Normalization concepts

In [32]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler,StandardScaler,RobustScaler

In [33]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

columns = ['SepalLength', 'SepalWidth','PetalLength','PetalWidth', 'Species']
data = pd.read_csv(url,header=None , names=columns)
data.head()

   SepalLength  SepalWidth  PetalLength  PetalWidth      Species
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

In [34]:
#Separate Features and target

x= data.iloc[:,:-1] #Numerical Features
y= data['Species'] #Target Variable

In [35]:
#Min-Max Normalization
#Scales data to a fixed range, usually[0, 1].

minmax_scaler = MinMaxScaler()
x_minmax = minmax_scaler.fit_transform(x)

pd.DataFrame(x_minmax,columns=x.columns).head()

   SepalLength  SepalWidth  PetalLength  PetalWidth
0     0.222222    0.625000     0.067797    0.041667
1     0.166667    0.416667     0.067797    0.041667
2     0.111111    0.500000     0.050847    0.041667
3     0.083333    0.458333     0.084746    0.041667
4     0.194444    0.666667     0.067797    0.041667

In [36]:
#Standardization(Z-score Normalization)
#Centers the data around zero with unit varience

standard_scaler = StandardScaler()
x_standard = standard_scaler.fit_transform(x)

pd.DataFrame(x_standard,columns=x.columns).head()

   SepalLength  SepalWidth  PetalLength  PetalWidth
0    -0.900681    1.032057    -1.341272   -1.312977
1    -1.143017   -0.124958    -1.341272   -1.312977
2    -1.385353    0.337848    -1.398138   -1.312977
3    -1.506521    0.106445    -1.284407   -1.312977
4    -1.021849    1.263460    -1.341272   -1.312977

In [37]:
#Robust Scaling
#Scales the data using statistics that are robust to outliers

robust_scaler = RobustScaler()
x_robust = robust_scaler.fit_transform(x)

pd.DataFrame(x_robust,columns=x.columns).head()

   SepalLength  SepalWidth  PetalLength  PetalWidth
0    -0.538462         1.0    -0.842857   -0.733333
1    -0.692308         0.0    -0.842857   -0.733333
2    -0.846154         0.4    -0.871429   -0.733333
3    -0.923077         0.2    -0.814286   -0.733333
4    -0.615385         1.2    -0.842857   -0.733333