<a href="https://colab.research.google.com/github/Nihalht/ML_LAB-PR-s/blob/main/ML_LAB_4b.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Nihal H T lab - 4b **

Data Normalization concepts - Without Lib using math

In [21]:
import pandas as pd
import numpy as np

In [22]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

columns = ['SepalLength', 'SepalWidth','PetalLength','PetalWidth', 'Species']
data = pd.read_csv(url,header=None , names=columns)

x=data.iloc[:,:-1]

In [23]:
#Define Custom Min-Max Normalization Function
def min_max_normalization(column):
  min_val = column.min()
  max_val = column.max()
  return (column - min_val) / (max_val - min_val)

In [29]:
#Apply Min-Max Normalization

x_minmax = x.apply(min_max_normalization)
x_minmax.head()

   SepalLength  SepalWidth  PetalLength  PetalWidth
0     0.222222    0.625000     0.067797    0.041667
1     0.166667    0.416667     0.067797    0.041667
2     0.111111    0.500000     0.050847    0.041667
3     0.083333    0.458333     0.084746    0.041667
4     0.194444    0.666667     0.067797    0.041667

In [30]:
#define custom z- score normalization functions
def z_score_normalization(column):
  mean_val = column.mean()
  std_val = column.std()
  return (column - mean_val) / std_val

In [31]:
#Apply Z-score normalization
x_zscore = x.apply(z_score_normalization)
x_zscore.head()

   SepalLength  SepalWidth  PetalLength  PetalWidth
0    -0.897674    1.028611    -1.336794   -1.308593
1    -1.139200   -0.124540    -1.336794   -1.308593
2    -1.380727    0.336720    -1.393470   -1.308593
3    -1.501490    0.106090    -1.280118   -1.308593
4    -1.018437    1.259242    -1.336794   -1.308593

In [36]:
#define Custom Robust scaling function
def robust_scaling(column):
  median_val = column.median()
  q1 = column.quantile(0.25)
  q3 = column.quantile(0.75)
  return (column - median_val) / (q3 - q1)

In [37]:
#Apply Robust Scaling
x_robust = x.apply(robust_scaling)
x_robust.head()

   SepalLength  SepalWidth  PetalLength  PetalWidth
0    -0.538462         1.0    -0.842857   -0.733333
1    -0.692308         0.0    -0.842857   -0.733333
2    -0.846154         0.4    -0.871429   -0.733333
3    -0.923077         0.2    -0.814286   -0.733333
4    -0.615385         1.2    -0.842857   -0.733333